name: Container Terraform

on:
  workflow_dispatch:
  
jobs:
  plan:
    name: Test Self Hosted
    runs-on: ubuntu-latest
    container: hashicorp/terraform:latest
    
    steps:
      - name: Check terraform version 
        run: terraform --version 
      
      - name: Initialise 
        run: terraform init
