on:
  push:
    branches: [ "main" ]
    
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:

        # Checkout the Repository
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
        
        # login to Azure CLI
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
       
       # Build and push image to container registry
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build SimpleWorkerService -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/SimpleWorkerService:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/SimpleWorkerService:${{ github.sha }}

        # Deploy to a container instance
        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/SimpleWorkerService:${{ github.sha }}
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: aci-SimpleWorkerService
            location: 'uk south'
