#
name: Pull Request Workflow
on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

# on pr - run lint, tests, checkov in parellel 
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:

        # Checkout the Repository
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
        



