name: Call a reusable workflow

on:
  workflow_dispatch:
  

jobs:
  call-reusable-workflow-20:
    uses: RukayaOK/reusable/.github/workflows/test-workflowcall.yml@main
    with:
      username: henry
    secrets: inherit
