name: Call a reusable workflow

on:
  workflow_dispatch:
  
  push:
    branches:
      - 'main'

jobs:
  call-reusable-workflow-20:
    uses: RukayaOK/reusable-actions/.github/workflows/test-workflowcall.yml@main
    with:
      username: henry
    secrets: inherit
